apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: guardrails-disallow-privileged
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: privileged-containers
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces: ["guardrails"]
      validate:
        message: "Privileged containers are not allowed in the guardrails namespace."
        pattern:
          spec:
            =(ephemeralContainers):
              - =(securityContext):
                  =(privileged): "false"
            =(initContainers):
              - =(securityContext):
                  =(privileged): "false"
            containers:
              - =(securityContext):
                  =(privileged): "false"
